apiVersion: v1
kind: ServiceAccount
metadata:
  name: resilience-board-sa
  namespace: resilience-board
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resilience-board-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resilience-board-binding
subjects:
- kind: ServiceAccount
  name: resilience-board-sa
  namespace: resilience-board
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: resilience-board-role
